name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write  # required for PyPI trusted publishing (OIDC)

concurrency:
  group: publish-pypi-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: pip

      - name: Build distributions
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          python -m build

      - name: Publish to PyPI (trusted publishing via OIDC)
        uses: pypa/gh-action-pypi-publish@release/v1
